version: '3.8'

services:
  # Vote-API
  vote-api:
    build:
      context: ./vote-api 
    environment:
      - PG_URL=postgres://vote_api:api123@postgres:5432/vote_api?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - network

  # PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: vote_api
      POSTGRES_PASSWORD: api123
      POSTGRES_DB: vote_api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

  # Node.js app
  web-client:
    build:
      context: ./web-client
    environment:
      - VOTE_API_BASE_URL=http://vote-api:8080
    ports:
      - "80:80"
    depends_on:
      - vote-api
    networks:
      - network
  
  # docs-app
  docs-app:
    build:
      context: ./docs 
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
