version: '3.9'

services:
  # Node.js app
  web-client:
    image: saadajugurtha/web-client:latest
    build:
      context: .
      dockerfile: ./web-client/Dockerfile
      target: production
    environment:
      - NODE_ENV=production
      - VOTE_API_BASE_URL=http://vote-api:8080
    ports:
      - "3000:3000"
    depends_on:
      - vote-api
    networks:
      - network

  # Vote-API
  vote-api:
    image: saadajugurtha/vote-api:latest
    build:
      context: .
      dockerfile: ./vote-api/Dockerfile
    environment:
      - PG_URL=postgres://vote_api:api123@postgres:5432/vote_api?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - network

  # PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: vote_api
      POSTGRES_PASSWORD: api123
      POSTGRES_DB: vote_api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network
  
  # docs-app
  docs-app:
    image: saadajugurtha/docs:latest
    build:
      context: .
      dockerfile: ./docs/Dockerfile
    ports:
      - "2000:2000"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
